### ISSUE TITLE
cx_Freeze Fatal Error: Unable to change DLL search path

### ISSUE THREAD

**Issue by lapdants** [DavidAI2024/Gemini-KD#1]
Error when trying to launch the .exe from a cloned rep. Any idea?

**Comment by florvexdev** [comment]
> Error when trying to launch the .exe from a cloned rep. Any idea?

@lapdants Now I'll find a solution and I will publish the fix today or tomorrow at the latest. Thank you so much for your support, leave a star if you want💓 @DavidAI2024

**Comment by DavidAI2024** [comment]
> Error when trying to launch the .exe from a cloned rep. Any idea?

If you can, show me a screenshot of the error you receive. Thank youIf you can, show me a screenshot of the error you receive. **Thank you @DavidAI2024 **

**Comment by florvexdev** [comment]
> @lapdants the problem should have been fixed in this **RELEASE** in version **[1.0.1](https://github.com/DavidAI2024/Gemini-KD/releases/tag/v1.0.1)** 💕
_I am closing this thread for any other issues you can open a new one_

@DavidAI2024
